version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "✅ Install phase complete"

  build:
    commands:
      - echo "✔ Version from pipeline: $MAJOR.$MINOR.$PATCH"
      - echo "🔧 Updating version in package.json using update_version.py..."
      - python update_version.py
      - echo "🧾 Contents of package.json after update:"
      - cat package.json
      - echo "🚀 Running Python app..."
      - python app.py

artifacts:
  files:
    - '**/*'
